### PR TITLE
[WIP] Send Notification when completed

### PR DESCRIPTION
**Pull request by ShiSheng233**
I'm sorry for the error commit on the master branch.
This feature is WIP, but it works.

image

### CODE REVIEW

**Comment by ShiSheng233** [comment]
I have corrected the error commit.

**Comment by ShiSheng233** [comment]
Next step is to

- [ ]  add thumbnail to the notification

**Comment by ShiSheng233** [comment]
> I have corrected the error commit.

Sorry……

Now all done~

**Comment by kannagi0303** [comment]
Thanks for your great help :)

Because this is the first time I use github to build an opensource project.
I'm not quite sure how to handle fork pull (merge works).

I'm sorry! Please give me some time to find out.

**Pull request merged**
